CREATE TABLE `user_registration` (
	`intId` BIGINT(20) AUTO_INCREMENT,
	`strFirstName` VARCHAR(80) DEFAULT NULL,
	`strLastName` VARCHAR(80) DEFAULT NULL,
	`strJobTitle` VARCHAR(80) NOT NULL,
	`strEmailAddress` VARCHAR(120) NOT NULL,
	`dtDateCreated` DATETIME DEFAULT NULL,
	PRIMARY KEY(`intId`)
) ENGINE=MYISAM AUTO_INCREMENT=1 CHARSET=UTF8;